# Generated by Django 4.2 on 2023-04-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_panchayath_app', '0002_citizen_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='surname',
        ),
    ]
