# Generated by Django 4.2 on 2023-04-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_panchayath_app', '0005_alter_citizen_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='address_line1',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
