# Generated by Django 4.2 on 2023-04-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_panchayath_app', '0009_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_panchayath_app.service'),
        ),
    ]
