# Generated by Django 4.2 on 2023-04-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_panchayath_app', '0010_application_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
