# Generated by Django 4.2 on 2023-04-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_panchayath_app', '0011_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
