# Generated by Django 4.2 on 2023-05-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_panchayath_app', '0013_alter_application_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('desc', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
